In [1]:
import pandas as ps
import numpy as np

# Write a Python program to add, subtract, multiple and divide two Pandas Series.

In [2]:
a=ps.array([1,2,3,4,5])
b=ps.array([6,7,8,9,10])
c=a+b
d=a*b
e=a-b
f=a/b
print("add",c)
print("mutliple",d)
print("subtract",e)
print("divide",f)

add <PandasArray>
[7, 9, 11, 13, 15]
Length: 5, dtype: int32
mutliple <PandasArray>
[6, 14, 24, 36, 50]
Length: 5, dtype: int32
subtract <PandasArray>
[-5, -5, -5, -5, -5]
Length: 5, dtype: int32
divide <PandasArray>
[0.16666666666666666, 0.2857142857142857, 0.375, 0.4444444444444444, 0.5]
Length: 5, dtype: float64


# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [3]:
a=np.random.randint(low=2,high=10,size=9).reshape(3,3)
a

array([[7, 9, 3],
       [7, 4, 6],
       [6, 9, 6]])

# Create a 3×3 numpy array, find out the Minimum,Maximum values and also their indices accordingly for each axes. Also find out the Statistical methods such as Standard Deviation,Cumulative sum and product.

In [31]:
a=np.random.randint(low=2,high=10,size=9).reshape(3,3)
print(a.max())
print(a.min())
print(np.cumsum(a))
print(np.std(a))
print(np.cumprod(a))

9
4
[ 4 11 15 21 27 32 37 46 55]
1.7916128329552332
[      4      28     112     672    4032   20160  100800  907200 8164800]


# Illustrate the concept of splitting by taking random positive values and also implementing different stacking methods on them.

In [4]:
a=np.random.randint(low=2,high=10,size=9).reshape(3,3)
b=np.random.randint(low=2,high=10,size=9).reshape(3,3)


print(np.vstack((a,b)))
print("-----------------------------------------------")
print(np.hstack((a,b)))

[[3 9 4]
 [8 8 8]
 [2 5 8]
 [3 7 4]
 [9 5 7]
 [5 7 9]]
-----------------------------------------------
[[3 9 4 3 7 4]
 [8 8 8 9 5 7]
 [2 5 8 5 7 9]]


# Write a Pandas program to change the order of index of a given series.

In [65]:
a=ps.DataFrame({"data":[1,3,45,5,6,67,7],
               },index=['a','b','c','d','e','f','g'])
print(a)
c=a.reindex(['a','c','d','b','f','e','g'])
c

   data
a     1
b     3
c    45
d     5
e     6
f    67
g     7


data
a     1
c    45
d     5
b     3
f    67
e     6
g     7

# Write a Python program to convert a Panda module Series to Python list  and it's type


In [110]:
panda=ps.Series([1,2,3,4,5,6])
print(panda)
print(type(panda))
print("------------------------------")
a=(panda.tolist())
print(a)
print(type(a))

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>
------------------------------
[1, 2, 3, 4, 5, 6]
<class 'list'>


# Write a Pandas program to create todays date

In [89]:
print(pd.to_datetime(str(datetime.today()), format='%Y-%m-%d'))


2020-01-04 14:44:11.712102


 #  Write a Pandas program to select the rows where the score is missing, i.e. is NaN 


In [121]:
exam_data = ps.DataFrame({"name": ['Sachin', 'Ganguly', 'Kohli', 'Johnson', 'Taylor','Waugh', 'Yuvraj', 'Kambli', 'Srinath', 'Munaf'],
    "score":[12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    "attempts":[1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    "qualify":['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']},index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'] )
print(exam_data)
(exam_data[exam_data['score'].isnull()])

      name  score  attempts qualify
a   Sachin   12.5         1     yes
b  Ganguly    9.0         3      no
c    Kohli   16.5         2     yes
d  Johnson    NaN         3      no
e   Taylor    9.0         2      no
f    Waugh   20.0         3     yes
g   Yuvraj   14.5         1     yes
h   Kambli    NaN         1      no
i  Srinath    8.0         2      no
j    Munaf   19.0         1     yes


name  score  attempts qualify
d  Johnson    NaN         3      no
h   Kambli    NaN         1      no

In [101]:
f = pd.DataFrame({'': ['one', 'one', 'one', 'two', 'two','two'],
                   'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'baz': [1, 2, 3, 4, 5, 6],
                   'zoo': ['x', 'y', 'z', 'q', 'w', 't']})
print(f)
f.pivot(index='foo', columns='bar', values='baz')

   foo bar  baz zoo
0  one   A    1   x
1  one   B    2   y
2  one   C    3   z
3  two   A    4   q
4  two   B    5   w
5  two   C    6   t


bar  A  B  C
foo         
one  1  2  3
two  4  5  6

# Illustrate the difference between ravel and flatten by taking considering multidimensional array.

In [157]:
m=np.array([[1,2,3,4,5,6],[1,2,33,4,4,6]])
print(m)
print("flatten",m.flatten())
print("------------------------------")
print("ravel",m.ravel())
print("------------------------------")
print(m.reshape(-1))
print(np.ravel(m, order='F'))
print("ravel",m.ravel())

[[ 1  2  3  4  5  6]
 [ 1  2 33  4  4  6]]
flatten [ 1  2  3  4  5  6  1  2 33  4  4  6]
------------------------------
ravel [ 1  2  3  4  5  6  1  2 33  4  4  6]
------------------------------
[ 1  2  3  4  5  6  1  2 33  4  4  6]
[ 1  1  2  2  3 33  4  4  5  4  6  6]
ravel [ 1  2  3  4  5  6  1  2 33  4  4  6]
